# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Corinne Butta
tagline:          ''
description:      ''
url:              
baseurl:          http://cbutta0.github.io

author:
  name:           'Corinne Butta'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
